compressionLevel: mixed

enableGlobalCache: true

nodeLinker: node-modules

catalog:
  '@docusaurus/core': 3.7.0
  '@docusaurus/module-type-aliases': 3.7.0
  '@docusaurus/preset-classic': 3.7.0
  '@docusaurus/tsconfig': 3.7.0
  '@docusaurus/types': 3.7.0
  '@mj-studio/js-util': 1.1.14
  '@types/invariant': ^2
  '@types/react': 19.0.0
  del-cli: ^5.1.0
  expo: ^53.0.0
  query-string: ^9.0.0
  react: 19.0.0
  react-dom: 19.0.0
  react-native: 0.79.2
  react-native-builder-bob: 0.40.7
  typescript: 5.3.3
  zx: 8.8.5
